### ISSUE TITLE
https://bscgas.info/gas CORS misconfig

### ISSUE THREAD

**Issue by pertsev** [werlang/bscgas#1]
Hi! Looks like your API could not be accessed from any other domains except `bscgas.info`

![image](https://user-images.githubusercontent.com/11399003/120531909-cda5f800-c3e7-11eb-9cd9-728a95b5b4f0.png)

Could you fix that? I would like to use it.

**Comment by dan1kov** [comment]
The same problem

**Comment by werlang** [comment]
This issue should now be fixed.
Thanks for the feedback.

**Comment by maliyshock** [comment]
@werlang 
Well... I still got this... Did you really fix that?

**Comment by werlang** [comment]
That's weird. I just fetched and received a response.

![image](https://user-images.githubusercontent.com/19828711/128093545-94292105-133a-4f1b-a7cf-4aab89f4445a.png)

**Comment by maliyshock** [comment]
![image](https://user-images.githubusercontent.com/7099817/128094735-9625a3b3-750e-4e32-bcaa-d5325a562494.png)
I getting this one.
Did I mess with headers?
![image](https://user-images.githubusercontent.com/7099817/128094813-c6732eef-df73-4f6a-8018-b1e43fe3a1e1.png)

**Comment by werlang** [comment]
> ![image](https://user-images.githubusercontent.com/7099817/128094735-9625a3b3-750e-4e32-bcaa-d5325a562494.png)
> I getting this one.
> Did I mess with headers?
> ![image](https://user-images.githubusercontent.com/7099817/128094813-c6732eef-df73-4f6a-8018-b1e43fe3a1e1.png)

Yes. Remove the 'mode' and 'Content-type' options. They are used for POST and PUT methods.
You could also remove the headers argument, as you are using a GET request, they are not needed.

**Comment by maliyshock** [comment]
Ok, thank you! Sorry for the interruption.

**Comment by maliyshock** [comment]
Hey guys. Recently I started getting errors once again. 
Example above `await (await fetch('https://bscgas.info/gas')).json()` does not work as well
![image](https://user-images.githubusercontent.com/7099817/131172077-6141e2aa-04eb-4dbb-b138-6a96fd294515.png)

Gould, you check once again?

**Comment by werlang** [comment]
> Hey guys. Recently I started getting errors once again.
> Example above `await (await fetch('https://bscgas.info/gas')).json()` does not work as well
> ![image](https://user-images.githubusercontent.com/7099817/131172077-6141e2aa-04eb-4dbb-b138-6a96fd294515.png)
> 
> Gould, you check once again?

I cannot reproduce that error. I opened a console on google.com, just like you did, then pasted the code you provided. It worked fine.

**Comment by maliyshock** [comment]
Yes, right now it working again. I think there might be an issue on the server side because it did not work for 2-3 days. I even thought that my IP address was blocked or something, because of too many requests or something like that.
