### ISSUE TITLE
Can't create new API key

### ISSUE THREAD

**Issue by schwartzman** [werlang/bscgas#2]
In the key-creation modal, the cog in the submit button just spins forever.

**Comment by werlang** [comment]
Can you try again?
bscgas.info was experiencing a lot of downtime lately due to increase in traffic.
This issue should be solved now as the oracle was moved to a different, more robust server.

I'll be here to solve any remaining issues.

**Comment by schwartzman** [comment]
Appears to be fixed now. Thank you for the update.
